### ISSUE TITLE
After several page have downloaded MP4 files are skipped

### ISSUE THREAD

**Issue by riznob** [itsankoff/gopro-plus#1]
After several pages are downloaded it appears that [the response to the download call](https://github.com/itsankoff/gopro-plus/blob/master/main.py#L114) does include any MP4 files that were included in [the media ids requested](https://github.com/itsankoff/gopro-plus/blob/master/main.py#L106).

I'll admit this seems to be a defect in the gopro api response.

**Comment by itsankoff** [comment]
Closing this issues since it is glitch in GoPro API, not in the codebase itself
