### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by oscaralon11** [itsankoff/gopro-plus#3]
I keep getting this error...:

GX010374.MP4 could not be downloaded: [Errno 2] No such file or directory: './download/GX010374.MP4'

What am i doing wrong?
Should I create the folder "download" myself and where should it be located?

Thanks in advance.

**Comment by riznob** [comment]
@oscaralon11 If you are running this from the cloned repo directory, the `download` directory already exists. If not, you will need to create it.

On another note, [my fork](https://github.com/riznob/gopro-plus) of the repo might be a better option. I was not seeing video files downloaded in the zip after about page 7. If you see the same behavior, try using [my fork](https://github.com/riznob/gopro-plus). [My fork](https://github.com/riznob/gopro-plus) also sets the created date of the files to the capture date, which is important to me.

**Comment by itsankoff** [comment]
As @riznob mentioned, if you clone the repo directly, it will use the `download` directory within the repo. Optionally, you can provide a different directory by using `-e DOWNLOAD_PATH` to store the files in any other destination.
