### ISSUE TITLE
COULD NOT GET AUTH_TOKEN ON GOOGLE CHROME

### ISSUE THREAD

**Issue by WanKa-zone** [itsankoff/gopro-plus#4]
Could not find server-io on the Network Tab and Headers tab on the Developer Tools console.
![image](https://github.com/itsankoff/gopro-plus/assets/45703375/b72e49ee-b730-4db4-8778-9ba2a844ae42)

Google Chrome Ver. 122.0.6261.129

**Comment by itsankoff** [comment]
Hey, you will need to search for this request after you log in and you need to have the console before login, so the dev tools can record the network requests.

**Comment by itsankoff** [comment]
Closing the issue. In case the issue persist you can look for some other requests after you successfully log in
