### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by WanKa-zone** [itsankoff/gopro-plus#7]
Keep coming up with Error code on Container Manager
![image](https://github.com/user-attachments/assets/7e377835-4d82-453b-bab9-80bce871e7a0)

Here is my docker run code:
docker run -d \
  --name itsankoff-gopro \
  -e AUTH_TOKEN=<gopro-auth-token> \
  -e USER_ID=<gopro-user-id> \
  -e DOWNLOAD_PATH="/volume1/GoPro" \
  itsankoff/gopro:latest

**Comment by MrRebooting** [comment]
Same issue. My folder /volume1/GoPro does exist.

**Comment by itsankoff** [comment]
@WanKa-zone @MrRebooting folks,

Thanks for reporting the issue. Indeed it was a problem especially if you decided to change the `DOWNLOAD_PATH`.
I fixed the problem and released a new docker image:

https://hub.docker.com/layers/itsankoff/gopro/1.5.3/images/sha256-61123b32d9510cbfad235ce92c20bf4555fa9cba64db100f74abd211b80b86ee

Now there are instructions for downloading directly on the host machine using a volume attachment (see the `master` or `1.5.3` README.md or the docker image description in the Docker Hub.

Let me know if you experience any other issues.
Happy New Year! 🎉

**Comment by MrRebooting** [comment]
@itsankoff Thanks for the quick fix but the folder seems to be created at the wrong place. I already have a folder created at /volume1/GoPro and when I performed the docker run... it says: Creating download directory: /volume1/GoPro

The download seems to work: downloading to /volume1/GoPro/1_page.zip

But the files are not in my folder. I perform a find and they seems to be in a temporary folder: ./volume1/@docker/btrfs/subvolumes/8d2d72d9e4c6858e4f026**********eb7161fd71992c2/volume1/GoPro/1_page.zip

**Comment by MrRebooting** [comment]
@itsankoff I think I have an issue with the -v ( I used previously the -e DOWNLOAD_PATH).
-v </volume1/GoPro>:/volume1/GoPro

Resulting:
-ash: :/volume1/GoPro: No such file or directory

**Comment by MrRebooting** [comment]
@itsankoff I got it finally. Thanks again. 
By chance, anyway to download the media without zipped?
